name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 16

    steps:
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      # Additional steps for building the website if needed

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.MY_PERSONAL_PROFILE }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 ec2-user@3.130.110.132 "cd /var/www/html && git pull origin main"
        env:
          SSH_AUTH_SOCK: ${{ steps.start-ssh-agent.outputs.ssh-agent-socket }}
